/**
 * @file config.cpp
 * @brief Implementation of configuration I/O
 * @author Thanh Nguyen Canh <thanhnc@jaist.ac.jp>
 * @date 2026
 */

#include "hesfm/config.h"
#include <fstream>
#include <sstream>
#include <iostream>
#include <yaml-cpp/yaml.h>

namespace hesfm {

// =============================================================================
// HESFMConfig Implementation
// =============================================================================

void HESFMConfig::loadFromROS(/* ros::NodeHandle& nh */) {
    // This would be implemented with ROS parameter server access
    // Example:
    // nh.param("uncertainty/w_semantic", uncertainty.w_semantic, 0.4);
    // nh.param("uncertainty/w_spatial", uncertainty.w_spatial, 0.2);
    // etc.
    
    // For now, use defaults
}

bool HESFMConfig::saveToYAML(const std::string& filepath) const {
    std::ofstream file(filepath);
    if (!file.is_open()) {
        std::cerr << "Failed to open file for writing: " << filepath << std::endl;
        return false;
    }
    
    file << "# HESFM Configuration\n";
    file << "# Generated by HESFM v" << HESFM_VERSION_STRING << "\n\n";
    
    // Uncertainty configuration
    file << "uncertainty:\n";
    file << "  w_semantic: " << uncertainty.w_semantic << "\n";
    file << "  w_spatial: " << uncertainty.w_spatial << "\n";
    file << "  w_observation: " << uncertainty.w_observation << "\n";
    file << "  w_temporal: " << uncertainty.w_temporal << "\n";
    file << "  spatial_radius: " << uncertainty.spatial_radius << "\n";
    file << "  min_neighbors: " << uncertainty.min_neighbors << "\n";
    file << "  sigma_range: " << uncertainty.sigma_range << "\n";
    file << "  sigma_density: " << uncertainty.sigma_density << "\n";
    file << "  sigma_angle: " << uncertainty.sigma_angle << "\n";
    file << "\n";
    
    // Primitive configuration
    file << "primitives:\n";
    file << "  target_primitives: " << primitive.target_primitives << "\n";
    file << "  min_points_per_primitive: " << primitive.min_points_per_primitive << "\n";
    file << "  conflict_threshold: " << primitive.conflict_threshold << "\n";
    file << "  regularization: " << primitive.regularization << "\n";
    file << "  uncertainty_weight_lambda: " << primitive.uncertainty_weight_lambda << "\n";
    file << "  use_incremental_updates: " << (primitive.use_incremental_updates ? "true" : "false") << "\n";
    file << "  incremental_max_distance: " << primitive.incremental_max_distance << "\n";
    file << "  full_rebuild_interval: " << primitive.full_rebuild_interval << "\n";
    file << "  num_classes: " << primitive.num_classes << "\n";
    file << "\n";
    
    // Kernel configuration
    file << "kernel:\n";
    file << "  length_scale_min: " << kernel.length_scale_min << "\n";
    file << "  length_scale_max: " << kernel.length_scale_max << "\n";
    file << "  uncertainty_threshold: " << kernel.uncertainty_threshold << "\n";
    file << "  uncertainty_low: " << kernel.uncertainty_low << "\n";
    file << "  gamma: " << kernel.gamma << "\n";
    file << "  reachability_lambda: " << kernel.reachability_lambda << "\n";
    file << "  traversable_classes: [";
    bool first = true;
    for (int cls : kernel.traversable_classes) {
        if (!first) file << ", ";
        file << cls;
        first = false;
    }
    file << "]\n";
    file << "\n";
    
    // Map configuration
    file << "map:\n";
    file << "  frame_id: \"" << map.frame_id << "\"\n";
    file << "  resolution: " << map.resolution << "\n";
    file << "  origin_x: " << map.origin_x << "\n";
    file << "  origin_y: " << map.origin_y << "\n";
    file << "  origin_z: " << map.origin_z << "\n";
    file << "  size_x: " << map.size_x << "\n";
    file << "  size_y: " << map.size_y << "\n";
    file << "  size_z: " << map.size_z << "\n";
    file << "  num_classes: " << map.num_classes << "\n";
    file << "  log_odds_min: " << map.log_odds_min << "\n";
    file << "  log_odds_max: " << map.log_odds_max << "\n";
    file << "\n";
    
    // Navigation configuration
    file << "navigation:\n";
    file << "  costmap_height_min: " << navigation.costmap_height_min << "\n";
    file << "  costmap_height_max: " << navigation.costmap_height_max << "\n";
    file << "  inflation_radius: " << navigation.inflation_radius << "\n";
    file << "  min_confidence: " << navigation.min_confidence << "\n";
    file << "\n";
    
    // Exploration configuration
    file << "exploration:\n";
    file << "  max_distance: " << exploration.max_distance << "\n";
    file << "  min_info_gain: " << exploration.min_info_gain << "\n";
    file << "  max_goals: " << exploration.max_goals << "\n";
    file << "  sensor_range: " << exploration.sensor_range << "\n";
    file << "  sensor_fov_horizontal: " << exploration.sensor_fov_horizontal << "\n";
    file << "  sensor_fov_vertical: " << exploration.sensor_fov_vertical << "\n";
    file << "  min_obstacle_distance: " << exploration.min_obstacle_distance << "\n";
    file << "\n";
    
    // Processing configuration
    file << "processing:\n";
    file << "  map_publish_rate: " << processing.map_publish_rate << "\n";
    file << "  costmap_publish_rate: " << processing.costmap_publish_rate << "\n";
    file << "  downsample_factor: " << processing.downsample_factor << "\n";
    file << "  num_threads: " << processing.num_threads << "\n";
    file << "  use_async_processing: " << (processing.use_async_processing ? "true" : "false") << "\n";
    file << "\n";

    // Sensor configuration
    file << "sensor:\n";
    file << "  min_range: " << processing.sensor_model.min_range << "\n";
    file << "  max_range: " << processing.sensor_model.max_range << "\n";
    
    file.close();
    return true;
}

bool HESFMConfig::loadFromYAML(const std::string& filepath) {
    YAML::Node root;
    try {
        root = YAML::LoadFile(filepath);
    } catch (const YAML::Exception& e) {
        std::cerr << "Failed to load YAML: " << e.what() << std::endl;
        return false;
    }

    // Helper lambdas for safe access
    auto getD = [](const YAML::Node& n, const std::string& k, double def) {
        return n[k] ? n[k].as<double>(def) : def;
    };
    auto getI = [](const YAML::Node& n, const std::string& k, int def) {
        return n[k] ? n[k].as<int>(def) : def;
    };
    auto getB = [](const YAML::Node& n, const std::string& k, bool def) {
        return n[k] ? n[k].as<bool>() : def;
    };
    auto getS = [](const YAML::Node& n, const std::string& k, const std::string& def) {
        return n[k] ? n[k].as<std::string>(def) : def;
    };

    if (auto u = root["uncertainty"]) {
        uncertainty.w_semantic    = getD(u, "w_semantic",    uncertainty.w_semantic);
        uncertainty.w_spatial     = getD(u, "w_spatial",     uncertainty.w_spatial);
        uncertainty.w_observation = getD(u, "w_observation", uncertainty.w_observation);
        uncertainty.w_temporal    = getD(u, "w_temporal",    uncertainty.w_temporal);
        uncertainty.spatial_radius = getD(u, "spatial_radius", uncertainty.spatial_radius);
        uncertainty.min_neighbors  = getI(u, "min_neighbors",  uncertainty.min_neighbors);
        uncertainty.sigma_range    = getD(u, "sigma_range",    uncertainty.sigma_range);
        uncertainty.sigma_density  = getD(u, "sigma_density",  uncertainty.sigma_density);
        uncertainty.sigma_angle    = getD(u, "sigma_angle",    uncertainty.sigma_angle);
        uncertainty.normalizeWeights();
    }

    YAML::Node primitive_node = root["primitives"] ? root["primitives"] : root["primitive"];
    if (primitive_node) {
        const auto& p = primitive_node;
        primitive.target_primitives        = getI(p, "target_primitives",        primitive.target_primitives);
        primitive.min_points_per_primitive  = getI(p, "min_points_per_primitive", primitive.min_points_per_primitive);
        primitive.conflict_threshold       = getD(p, "conflict_threshold",       primitive.conflict_threshold);
        primitive.regularization           = getD(p, "regularization",           primitive.regularization);
        primitive.uncertainty_weight_lambda = getD(p, "uncertainty_weight_lambda", primitive.uncertainty_weight_lambda);
        primitive.use_incremental_updates   = getB(p, "use_incremental_updates", primitive.use_incremental_updates);
        primitive.incremental_max_distance  = getD(p, "incremental_max_distance", primitive.incremental_max_distance);
        primitive.full_rebuild_interval     = getI(p, "full_rebuild_interval", primitive.full_rebuild_interval);
        primitive.num_classes               = getI(p, "num_classes",             primitive.num_classes);
    }

    if (auto k = root["kernel"]) {
        kernel.length_scale_min      = getD(k, "length_scale_min",      kernel.length_scale_min);
        kernel.length_scale_max      = getD(k, "length_scale_max",      kernel.length_scale_max);
        kernel.uncertainty_threshold = getD(k, "uncertainty_threshold",  kernel.uncertainty_threshold);
        kernel.uncertainty_low       = getD(k, "uncertainty_low",        kernel.uncertainty_low);
        kernel.gamma                 = getD(k, "gamma",                  kernel.gamma);
        kernel.reachability_lambda   = getD(k, "reachability_lambda",    kernel.reachability_lambda);
        if (k["traversable_classes"]) {
            kernel.traversable_classes.clear();
            for (const auto& cls : k["traversable_classes"]) {
                kernel.traversable_classes.insert(cls.as<int>());
            }
        }
    }

    if (auto m = root["map"]) {
        map.frame_id     = getS(m, "frame_id",     map.frame_id);
        map.resolution   = getD(m, "resolution",   map.resolution);
        map.origin_x     = getD(m, "origin_x",     map.origin_x);
        map.origin_y     = getD(m, "origin_y",     map.origin_y);
        map.origin_z     = getD(m, "origin_z",     map.origin_z);
        map.size_x       = getD(m, "size_x",       map.size_x);
        map.size_y       = getD(m, "size_y",       map.size_y);
        map.size_z       = getD(m, "size_z",       map.size_z);
        map.num_classes   = getI(m, "num_classes",  map.num_classes);
        map.log_odds_min  = getD(m, "log_odds_min", map.log_odds_min);
        map.log_odds_max  = getD(m, "log_odds_max", map.log_odds_max);
    }

    if (auto n = root["navigation"]) {
        navigation.costmap_height_min = getD(n, "costmap_height_min", navigation.costmap_height_min);
        navigation.costmap_height_max = getD(n, "costmap_height_max", navigation.costmap_height_max);
        navigation.inflation_radius   = getD(n, "inflation_radius",   navigation.inflation_radius);
        navigation.min_confidence     = getD(n, "min_confidence",      navigation.min_confidence);
    }

    if (auto e = root["exploration"]) {
        exploration.max_distance  = getD(e, "max_distance",  exploration.max_distance);
        exploration.min_info_gain = getD(e, "min_info_gain", exploration.min_info_gain);
        exploration.max_goals     = getI(e, "max_goals",     exploration.max_goals);
        exploration.sensor_range  = getD(e, "sensor_range",  exploration.sensor_range);
        exploration.sensor_fov_horizontal = getD(e, "sensor_fov_horizontal", exploration.sensor_fov_horizontal);
        exploration.sensor_fov_vertical   = getD(e, "sensor_fov_vertical",   exploration.sensor_fov_vertical);
    }

    if (auto pr = root["processing"]) {
        processing.map_publish_rate     = getD(pr, "map_publish_rate",     processing.map_publish_rate);
        processing.costmap_publish_rate = getD(pr, "costmap_publish_rate", processing.costmap_publish_rate);
        processing.downsample_factor    = getI(pr, "downsample_factor",    processing.downsample_factor);
        processing.num_threads          = getI(pr, "num_threads",          processing.num_threads);
        processing.use_async_processing = getB(pr, "use_async_processing", processing.use_async_processing);
    }

    if (auto s = root["sensor"]) {
        processing.sensor_model.min_range = getD(s, "min_range", processing.sensor_model.min_range);
        processing.sensor_model.max_range = getD(s, "max_range", processing.sensor_model.max_range);
    }

    return true;
}

} // namespace hesfm
