/**
 * @file config.cpp
 * @brief Implementation of configuration I/O
 * @author Thanh Nguyen Canh <thanhnc@jaist.ac.jp>
 * @date 2026
 */

#include "hesfm/config.h"
#include <fstream>
#include <sstream>
#include <iostream>

namespace hesfm {

// =============================================================================
// HESFMConfig Implementation
// =============================================================================

void HESFMConfig::loadFromROS(/* ros::NodeHandle& nh */) {
    // This would be implemented with ROS parameter server access
    // Example:
    // nh.param("uncertainty/w_semantic", uncertainty.w_semantic, 0.4);
    // nh.param("uncertainty/w_spatial", uncertainty.w_spatial, 0.2);
    // etc.
    
    // For now, use defaults
}

bool HESFMConfig::saveToYAML(const std::string& filepath) const {
    std::ofstream file(filepath);
    if (!file.is_open()) {
        std::cerr << "Failed to open file for writing: " << filepath << std::endl;
        return false;
    }
    
    file << "# HESFM Configuration\n";
    file << "# Generated by HESFM v" << HESFM_VERSION_STRING << "\n\n";
    
    // Uncertainty configuration
    file << "uncertainty:\n";
    file << "  w_semantic: " << uncertainty.w_semantic << "\n";
    file << "  w_spatial: " << uncertainty.w_spatial << "\n";
    file << "  w_observation: " << uncertainty.w_observation << "\n";
    file << "  w_temporal: " << uncertainty.w_temporal << "\n";
    file << "  spatial_radius: " << uncertainty.spatial_radius << "\n";
    file << "  min_neighbors: " << uncertainty.min_neighbors << "\n";
    file << "  sigma_range: " << uncertainty.sigma_range << "\n";
    file << "  sigma_density: " << uncertainty.sigma_density << "\n";
    file << "  sigma_angle: " << uncertainty.sigma_angle << "\n";
    file << "\n";
    
    // Primitive configuration
    file << "primitive:\n";
    file << "  target_primitives: " << primitive.target_primitives << "\n";
    file << "  min_points_per_primitive: " << primitive.min_points_per_primitive << "\n";
    file << "  conflict_threshold: " << primitive.conflict_threshold << "\n";
    file << "  regularization: " << primitive.regularization << "\n";
    file << "  uncertainty_weight_lambda: " << primitive.uncertainty_weight_lambda << "\n";
    file << "  num_classes: " << primitive.num_classes << "\n";
    file << "\n";
    
    // Kernel configuration
    file << "kernel:\n";
    file << "  length_scale_min: " << kernel.length_scale_min << "\n";
    file << "  length_scale_max: " << kernel.length_scale_max << "\n";
    file << "  uncertainty_threshold: " << kernel.uncertainty_threshold << "\n";
    file << "  uncertainty_low: " << kernel.uncertainty_low << "\n";
    file << "  gamma: " << kernel.gamma << "\n";
    file << "  reachability_lambda: " << kernel.reachability_lambda << "\n";
    file << "  traversable_classes: [";
    bool first = true;
    for (int cls : kernel.traversable_classes) {
        if (!first) file << ", ";
        file << cls;
        first = false;
    }
    file << "]\n";
    file << "\n";
    
    // Map configuration
    file << "map:\n";
    file << "  frame_id: \"" << map.frame_id << "\"\n";
    file << "  resolution: " << map.resolution << "\n";
    file << "  origin_x: " << map.origin_x << "\n";
    file << "  origin_y: " << map.origin_y << "\n";
    file << "  origin_z: " << map.origin_z << "\n";
    file << "  size_x: " << map.size_x << "\n";
    file << "  size_y: " << map.size_y << "\n";
    file << "  size_z: " << map.size_z << "\n";
    file << "  num_classes: " << map.num_classes << "\n";
    file << "  log_odds_min: " << map.log_odds_min << "\n";
    file << "  log_odds_max: " << map.log_odds_max << "\n";
    file << "\n";
    
    // Navigation configuration
    file << "navigation:\n";
    file << "  costmap_height_min: " << navigation.costmap_height_min << "\n";
    file << "  costmap_height_max: " << navigation.costmap_height_max << "\n";
    file << "  inflation_radius: " << navigation.inflation_radius << "\n";
    file << "  min_confidence: " << navigation.min_confidence << "\n";
    file << "\n";
    
    // Exploration configuration
    file << "exploration:\n";
    file << "  max_distance: " << exploration.max_distance << "\n";
    file << "  min_info_gain: " << exploration.min_info_gain << "\n";
    file << "  max_goals: " << exploration.max_goals << "\n";
    file << "  sensor_range: " << exploration.sensor_range << "\n";
    file << "  sensor_fov_horizontal: " << exploration.sensor_fov_horizontal << "\n";
    file << "  sensor_fov_vertical: " << exploration.sensor_fov_vertical << "\n";
    file << "  min_obstacle_distance: " << exploration.min_obstacle_distance << "\n";
    file << "\n";
    
    // Processing configuration
    file << "processing:\n";
    file << "  map_publish_rate: " << processing.map_publish_rate << "\n";
    file << "  costmap_publish_rate: " << processing.costmap_publish_rate << "\n";
    file << "  downsample_factor: " << processing.downsample_factor << "\n";
    file << "  num_threads: " << processing.num_threads << "\n";
    
    file.close();
    return true;
}

bool HESFMConfig::loadFromYAML(const std::string& filepath) {
    std::ifstream file(filepath);
    if (!file.is_open()) {
        std::cerr << "Failed to open file for reading: " << filepath << std::endl;
        return false;
    }
    
    // Simple YAML parser (for production, use yaml-cpp)
    std::string line;
    std::string current_section;
    
    auto parseDouble = [](const std::string& value) -> double {
        try {
            return std::stod(value);
        } catch (...) {
            return 0.0;
        }
    };
    
    auto parseInt = [](const std::string& value) -> int {
        try {
            return std::stoi(value);
        } catch (...) {
            return 0;
        }
    };
    
    auto trim = [](const std::string& str) -> std::string {
        size_t start = str.find_first_not_of(" \t");
        size_t end = str.find_last_not_of(" \t");
        if (start == std::string::npos) return "";
        return str.substr(start, end - start + 1);
    };
    
    while (std::getline(file, line)) {
        // Skip comments and empty lines
        line = trim(line);
        if (line.empty() || line[0] == '#') continue;
        
        // Check for section header
        if (line.back() == ':' && line.find(':') == line.length() - 1) {
            current_section = line.substr(0, line.length() - 1);
            continue;
        }
        
        // Parse key-value pair
        size_t colon_pos = line.find(':');
        if (colon_pos == std::string::npos) continue;
        
        std::string key = trim(line.substr(0, colon_pos));
        std::string value = trim(line.substr(colon_pos + 1));
        
        // Remove quotes from string values
        if (value.front() == '"' && value.back() == '"') {
            value = value.substr(1, value.length() - 2);
        }
        
        // Assign values based on section and key
        if (current_section == "uncertainty") {
            if (key == "w_semantic") uncertainty.w_semantic = parseDouble(value);
            else if (key == "w_spatial") uncertainty.w_spatial = parseDouble(value);
            else if (key == "w_observation") uncertainty.w_observation = parseDouble(value);
            else if (key == "w_temporal") uncertainty.w_temporal = parseDouble(value);
            else if (key == "spatial_radius") uncertainty.spatial_radius = parseDouble(value);
            else if (key == "min_neighbors") uncertainty.min_neighbors = parseInt(value);
        }
        else if (current_section == "primitive") {
            if (key == "target_primitives") primitive.target_primitives = parseInt(value);
            else if (key == "min_points_per_primitive") primitive.min_points_per_primitive = parseInt(value);
            else if (key == "conflict_threshold") primitive.conflict_threshold = parseDouble(value);
            else if (key == "num_classes") primitive.num_classes = parseInt(value);
        }
        else if (current_section == "kernel") {
            if (key == "length_scale_min") kernel.length_scale_min = parseDouble(value);
            else if (key == "length_scale_max") kernel.length_scale_max = parseDouble(value);
            else if (key == "uncertainty_threshold") kernel.uncertainty_threshold = parseDouble(value);
            else if (key == "gamma") kernel.gamma = parseDouble(value);
        }
        else if (current_section == "map") {
            if (key == "frame_id") map.frame_id = value;
            else if (key == "resolution") map.resolution = parseDouble(value);
            else if (key == "origin_x") map.origin_x = parseDouble(value);
            else if (key == "origin_y") map.origin_y = parseDouble(value);
            else if (key == "origin_z") map.origin_z = parseDouble(value);
            else if (key == "size_x") map.size_x = parseDouble(value);
            else if (key == "size_y") map.size_y = parseDouble(value);
            else if (key == "size_z") map.size_z = parseDouble(value);
            else if (key == "num_classes") map.num_classes = parseInt(value);
        }
        else if (current_section == "navigation") {
            if (key == "costmap_height_min") navigation.costmap_height_min = parseDouble(value);
            else if (key == "costmap_height_max") navigation.costmap_height_max = parseDouble(value);
            else if (key == "inflation_radius") navigation.inflation_radius = parseDouble(value);
        }
        else if (current_section == "exploration") {
            if (key == "max_distance") exploration.max_distance = parseDouble(value);
            else if (key == "min_info_gain") exploration.min_info_gain = parseDouble(value);
            else if (key == "max_goals") exploration.max_goals = parseInt(value);
            else if (key == "sensor_range") exploration.sensor_range = parseDouble(value);
        }
        else if (current_section == "processing") {
            if (key == "map_publish_rate") processing.map_publish_rate = parseDouble(value);
            else if (key == "costmap_publish_rate") processing.costmap_publish_rate = parseDouble(value);
            else if (key == "downsample_factor") processing.downsample_factor = parseInt(value);
            else if (key == "num_threads") processing.num_threads = parseInt(value);
        }
    }
    
    file.close();
    return true;
}

} // namespace hesfm
